type: container
children:
  tdp_enable:
    title: Enable TDP Controls
    type: bool
    default: False

  enforce_limits:
    title: Enforce Device TDP Limits
    type: bool
    tags: [ expert ]
    default: True

  tdp_error:
    title: Error
    type: display
    tags: [error]
    options: 
      nowrite: Can not write to ACPI Call file. ACPI Call is required for TDP.