type: container
title: Adjustor (TDP)
hint: Various TDP settings for handheld devices.
children:
  enable:
    title: Enable TDP Controls
    type: bool
    default: False

  set_limits:
    title: Enforce Device Limits
    type: bool
    default: True