type: container
title: General Settings
tags: [ advanced ]
children:
  enable:
    title: Enable TDP Controls
    type: bool
    default: False

  set_limits:
    title: Enforce Device Limits
    type: bool
    default: True