name: Publish to COPR

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy_copr:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - uses: actions/checkout@v3
      - name: Create spec file dir
        run: mkdir -p ./pkg/
      - name: Build spec file
        run: sed "s/REPLACE_VERSION/$(cat pyproject.toml | grep -E 'version = "[0-9\.]+"' -o | grep -E "[0-9\.]+" -o)/" adjustor.spec > ./pkg/adjustor.spec
      - name: Publish to COPR repo
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: git@github.com:hhd-dev/adjustor-copr.git
          BRANCH: main
          FOLDER: pkg
          SSH_PRIVATE_KEY: ${{ secrets.COPR_SSH_PRIVATE_KEY }}
          MESSAGE: Manual update
          SKIP_EMPTY_COMMITS: true
          # Do not clear any files
          CLEAR_GLOBS_FILE: .github/workflows/copr_glob.txt
          ssh_keyscan_types: rsa,ecdsa,ed25519
